apiVersion: v1
kind: Service
metadata:
  name: coredns-udp-svc-lb
  namespace: kube-system
  annotations:
    metallb.universe.tf/allow-shared-ip: coredns
spec:
  ports:
  - protocol: UDP
    port: 53
    targetPort: 53
  selector:
    k8s-app: kube-dns
  type: LoadBalancer
  loadBalancerIP: 172.17.255.10