---
apiVersion: apps/v1
kind: Deployment # Название нашего объекта Deployment
metadata:
  name: prod
spec:
  replicas: 3
  selector:
    matchLabels: # - это поды с меткой
      app: prod # app и ее значением web
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 100%
  template:
    metadata:
      labels:
        app: prod
    spec:
      containers:
      - name: prod
        image: chudinanton/nginx-otus:v.0.0.3
        livenessProbe:
          tcpSocket:
            port: 8000
        readinessProbe:
          httpGet:
            path: /index.html
            port: 8000
        volumeMounts:
          - name: app
            mountPath: /app
      initContainers:
        - name: html-gen
          image: busybox:musl
          command: ['sh', '-c', 'wget -O- https://bit.ly/otus-k8s-index-gen | sh']
          volumeMounts:
            - name: app
              mountPath: /app
      volumes:
        - name: app
          emptyDir: {}

