kind: Pod
apiVersion: v1
metadata:
  name: storage-pod
spec:
  containers:
    - name: my-frontend
      image: busybox
      volumeMounts:
      - mountPath: "/data"
        name: storage-pvc
      command: [ "sleep", "1000000" ]
  volumes:
    - name: storage-pvc
      persistentVolumeClaim:
        claimName: storage-pvc # defined in csi-pvc.yaml
