kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: iscsi-pvc-d
  annotations:
    volume.beta.kubernetes.io/storage-class: "iscsi-targetd-vg-iscsi"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
kind: Pod
apiVersion: v1
metadata:
  name: iscsi-app
spec:
  containers:
    - name: my-frontend
      image: busybox
      volumeMounts:
      - mountPath: "/data"
        name: storage-pvc
      command: [ "sleep", "1000000" ]
  volumes:
    - name: storage-pvc
      persistentVolumeClaim:
        claimName: iscsi-pvc-d