kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: iscsi-targetd-vg-iscsi
provisioner: iscsi-targetd
parameters:
# this id where the iscsi server is running
  targetPortal: 192.168.9.10:3260

# this is the iscsi server iqn
  iqn: iqn.2021-10.su.yogatour.k8s:storage-test

# this is the iscsi interface to be used, the default is default
# iscsiInterface: default

# this must be on eof the volume groups condifgured in targed.yaml, the default is vg-targetd
# volumeGroup: vg-targetd

# this is a comma separated list of initiators that will be give access to the created volumes, they must correspond to what you have configured in your nodes.
  initiators: iqn.2021-10.su.yogatour.k8s:node-1,iqn.2021-10.su.yogatour.k8s:node-2,iqn.2021-10.su.yogatour.k8s:node-3

# whether or not to use chap authentication for discovery operations
  chapAuthDiscovery: "false"

# whether or not to use chap authentication for session operations
  chapAuthSession: "false"

  fsType: xfs