kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: myclaim
spec:
#  storageClassName: iscsi-targetd-vg-iscsi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
