apiVersion: v1
kind: Pod
metadata:
  name: bash
  labels:
    app: bash
spec:
  serviceAccountName: vault-auth
  containers:
  - name: bash
    image: bash
    command: ["/bin/sh", "-ec", "sleep 3600"]
