kind: Deployment
apiVersion: apps/v1
metadata:
  name: nfs-test-rwm
spec:
  selector:
    matchLabels:
      app: nfs-test-rwm
  replicas: 3
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nfs-test-rwm
    spec:
      volumes:
      - name: host-volume
        persistentVolumeClaim:
          claimName: pvc1
      containers:
      - image: busybox
        name: busybox
        command: ["/bin/sh"]
        args: ["-c", "sleep 600"]
        volumeMounts:
        - name: host-volume
          mountPath: /mydata
