injector:
  # True if you want to enable vault agent injection.
  enabled: true

  replicas: 3

  leaderElector:
    enabled: false

  # Extra annotations to attach to the webhook
  webhookAnnotations: 
    cert-manager.io/inject-ca-from: default/injector-tls

  certs:
    secretName: injector-tls

server:  
  standalone:
    enabled: false

  extraEnvironmentVars:
    VAULT_ADDR: https://localhost:8200
    VAULT_CACERT: /vault/userconfig/vault-server-tls/vault.ca
    GOOGLE_REGION: global
    GOOGLE_PROJECT: geometric-orbit-325713
    GOOGLE_APPLICATION_CREDENTIALS: /vault/userconfig/kms-creds/chudinanton-gcp-key.json


  extraVolumes:
    - type: secret
      name: vault-server-tls
    - type: secret
      name: kms-creds

  ha:
    enabled: true

    config: |
      ui = true
      listener "tcp" {
        tls_disable = 0
        address = "[::]:8200"
        cluster_address = "[::]:8201"
        tls_cert_file = "/vault/userconfig/vault-server-tls/vault.crt"
        tls_key_file  = "/vault/userconfig/vault-server-tls/vault.key"
        tls_client_ca_file = "/vault/userconfig/vault-server-tls/vault.ca"
      }

      seal "gcpckms" {
        project     = "geometric-orbit-325713"
        region      = "global"
        key_ring    = "vault"
        crypto_key  = "vault-key"
      }

      storage "consul" {
        path = "vault-auto-unseal"
        address = "HOST_IP:8500"
      }

      service_registration "kubernetes" {}



ui:
  enabled: true