kind: Pod
apiVersion: v1
metadata:
  name: iscsi-app
spec:
  containers:
    - name: my-frontend
      image: busybox
      volumeMounts:
      - mountPath: "/data"
        name: storage-pvc
      command: [ "sleep", "1000000" ]
  volumes:
    - name: storage-pvc
      persistentVolumeClaim:
        claimName: iscsi-pvc