apiVersion: v1
kind: PersistentVolume
metadata:
  name: iscsi-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  iscsi:
     targetPortal: 192.168.9.10
     iqn: iqn.2021-10.su.yogatour.k8s:storage-test
     lun: 0
     fsType: 'xfs'
     readOnly: false