helmDefaults:
  createNamespace: true
  wait: true

repositories:
  - name: stable
    url: https://charts.helm.sh/stable

  - name: jetstack
    url: https://charts.jetstack.io

  - name: harbor
    url: https://helm.goharbor.io

  - name: nginx-stable
    url: https://helm.nginx.com/stable

releases:
  - name: nginx-ingress
    namespace: nginx-ingress
    chart: nginx-stable/nginx-ingress
    version: 0.10.1

  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: 1.5.3
    values:
      - installCRDs: true
    hooks:
      - events: ["postsync"]
        showlogs: true
        command: kubectl
        args: ["apply", "-f", "../cert-manager/cluster_issuer.yaml"]
      - events: ["postsync"]
        showlogs: true
        command: kubectl
        args: ["apply", "-f", "../cert-manager/cluster_issuer_stage.yaml"]        

  - name: harbor
    needs:
      - cert-manager/cert-manager
    namespace: harbor
    chart: harbor/harbor
    version: 1.7.2
    values:
      - ../harbor/values.yaml
    hooks:
      - events: ["presync"]
        showlogs: true
        command: "/bin/sh"
        args:
        - "-c"
        - >-
          kubectl get namespace "{{`{{ .Release.Namespace }}`}}" >/dev/null 2>&1 || kubectl create namespace "{{`{{ .Release.Namespace }}`}}";
