apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-list: chudinanton/emailservice:^v0.0
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/creds-3496798157
  name: emailservice
  namespace: argocd
spec:
  destination:
    namespace: microservices-demo
    server: https://34.107.22.41
  project: default
  source:
    helm:
      valueFiles:
      - values.yaml
    path: deploy/charts/emailservice
    repoURL: https://gitlab.com/chudinanton108/microservices-demo-argocd.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true    