apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microservices-demo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://gitlab.com/chudinanton108/microservices-demo-argocd.git'
    path: deploy/namespaces
    targetRevision: HEAD
    directory:
      recurse: true
      jsonnet: {}
  destination:
    server: 'https://34.107.22.41'
    namespace: microservices-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
