helmDefaults:
  createNamespace: true
  wait: true

repositories:
  - name: jetstack
    url: https://charts.jetstack.io

  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx

releases:
  - name: ingress-nginx
    namespace: ingress-nginx
    chart: ingress-nginx/ingress-nginx
    version: 4.0.1
    hooks:
      - events: ["presync"]
        showlogs: true
        command: "/bin/sh"
        args:
        - "-c"
        - >-
          kubectl get namespace "{{`{{ .Release.Namespace }}`}}" >/dev/null 2>&1 || kubectl create namespace "{{`{{ .Release.Namespace }}`}}";
    values:
      - ./nginx-ingress.values.yaml

  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: 1.5.3
    values:
      - installCRDs: true
    hooks:
      - events: ["postsync"]
        showlogs: true
        command: kubectl
        args: ["apply", "-f", "cert-manager/cluster_issuer.yaml"]
      - events: ["postsync"]
        showlogs: true
        command: kubectl
        args: ["apply", "-f", "cert-manager/cluster_issuer_stage.yaml"]        
      - events: ["presync"]
        showlogs: true
        command: "/bin/sh"
        args:
        - "-c"
        - >-
          kubectl get namespace "{{`{{ .Release.Namespace }}`}}" >/dev/null 2>&1 || kubectl create namespace "{{`{{ .Release.Namespace }}`}}";
